spring:
  application:
    name: zuul-server-demo
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
zuul:
  routes:
    demo:
      path: /demo/**
      serviceId: demo-service